# hubeet-vector-lite configuration file

# Networking
bind_addr = 0.0.0.0
port = 5555

# HNSW Parameters
dim = 384
M = 16
ef_construction = 200
ef_search = 512
max_levels = 16

# Inference
embedding_model_path = ./models/paraphrase-multilingual-MiniLM-L12-v2.hvl_model
save_interval = 15
max_text_length = 4096
persistence_path = dump.hvl

# Logging
log_level = 2
log_file = hvl.log
